### ISSUE TITLE
New Window does not do anything in Haiku

### ISSUE THREAD

**Issue by suhr** [SpartanJ/ecode#599]
In Haiku, `New Window` does not seem to do anything.

Tested versions: 0.7.1 and 0.7.2 (built using https://github.com/haikuports/haikuports/pull/12629).

**Comment by SpartanJ** [comment]
It seems that it doesn't work from the haikuport package distribution. It does work in the package I distribute in this repository. The reason is because it executing the binary without the full-path, only using the binary name, this was accidental, I pushed a fix (although I haven't tested it because I don't remember how to build the haikuport locally).

**Comment by SpartanJ** [comment]
BTW if this actually fix your issue I suggest to change the commit hash to #[84da362](https://github.com/SpartanJ/eepp/commit/84da3626f9eb3c3a5ab42708c5ab4f885e3c9dc9) since I haven't done any other changes yet since the release.

**Comment by suhr** [comment]
I built and run ecode with this change, but `New Window` still does not do anything.

**Comment by SpartanJ** [comment]
Mhh it seems that it has something to do with the haikuports package itself. That package build prevents to fork the process, even if I move the package outside the `/system/apps/ecode` still doesn't work. I have no idea why it doesn't work, it seems related to the packaging method, since some hpkg apps behave like single instance applications for some reason (including ecode). @begasus @waddlesplash can any of you give me some hint on why this might fail *only* when executed from the haiku package. The way it creates a new instance is by fork + execvp and works as expected when run from a non-packaged installation.

**Comment by waddlesplash** [comment]
84da3626f9eb3c3a5ab42708c5ab4f885e3c9dc9 looks correct to me. What error is occurring?

**Comment by SpartanJ** [comment]
@waddlesplash thanks for taking a look!
It's a little bit hard to explain, the video shows:

1. I open ecode from my local build (built from [84da362](https://github.com/SpartanJ/eepp/commit/84da3626f9eb3c3a5ab42708c5ab4f885e3c9dc9)), the "New Window" (fork and execvp) creates a new instance of the application with no problem.
2. I open ecode build from a local build with haikuports (using the same commit/source) and try to open a "New Window" (which forks the process) and nothing happens even though it's the exact same code.
3. Also tried to show that CudaText behaves the same (you cannot open it twice) and the Activity Monitor does open multiple times. But actually CudaText has that behaviour built-in so  it was a bad example, but I checked other applications and most of them behave this way even though they don't implement any single instance logic.

https://github.com/user-attachments/assets/5c7e9f0f-641f-4813-912b-bb1afafe0660

And this behaviour doesn't seem to have something to do with an incorrect implementation of that feature, for example: if I open a terminal (inside the editor) and try to open the application it won't work if run from the haiku package binary, but will work normally from my local build:

https://github.com/user-attachments/assets/34bf558b-c334-45ac-bc9b-d60e23faf65d

I don't know what is preventing ecode to run multiple instances if it's installed as a system app and how to avoid this issue.

**Comment by Begasus** [comment]
Checking a build with resource `app_flags B_MULTIPLE_LAUNCH;` if it fixes the issue. Will report back in a bit.

EDIT: that worked :) will push the change in abit.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/b4ea71ce-6392-4c42-991c-759a4876ee36" />

Fixed in: https://github.com/haikuports/haikuports/pull/12630

**Comment by SpartanJ** [comment]
Thank you very much @Begasus !
